### ISSUE TITLE
canto didn't displayed TUI

### ISSUE THREAD

**Issue by Busyvar** [themoken/canto-next#36]
Hi,

After setting  some new locales and font settings to Archlinux x64, canto-curses was not able to display his text UI.
Logs from daemon are available here :  http://ix.io/18z3 

thanks for your time,

PE

**Comment by themoken** [comment]
Yikes, json.load() can't decode your config file. Did you switch to a non UTF-8 locale?

**Comment by Buridan** [comment]
This configuration is utf-8 because $LANG returns _myLocaleName.UTF-8_ , terminal used is _unicode-rxvt_, and unicode glyph are correctly displayed by my font ,_inconsolata_ .

Some interesting facts : when canto-curses is halted manually (^C), this message is displayed : 
22:31:34 : CANTO-CURSES -> Exiting.

but his pid is kept into .config/canto/ folder, even if there is no more canto* processes running.
So i tried to remove pid and feeds files then relaunching canto-curses, but nothing changed.
